#---------------------------------------------------------------------------------------------------
# system
#---------------------------------------------------------------------------------------------------

[general]
live_config_reload = false

[env]
TERM = "alacritty"

[window]
dynamic_title = false
opacity = 0.80

[debug]
log_level = "Off"
persistent_logging = false
print_events = false
render_timer = false

#colors
#---------------------------------------------------------------------------------------------------

[colors]
draw_bold_text_with_bright_colors = false

[colors.cursor]
cursor = "#ff0000"

[colors.normal]
black = "#000000"
blue = "#0000ff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

# cursor
#---------------------------------------------------------------------------------------------------

[cursor]
blink_interval = 500
blink_timeout = 0
unfocused_hollow = true

[cursor.style]
shape = "block"
blinking = "Always"

# font
#---------------------------------------------------------------------------------------------------

[font]
builtin_box_drawing = false
size = 17.0

[font.normal]
family = "Jetbrains Mono"
style = "Regular"

[font.bold]
family = "Jetbrains Mono"
style = "Bold"

[font.italic]
family = "Jetbrains Mono"
style = "Italic"

[font.bold_italic]
family = "Jetbrains Mono"
style = "Bold Italic"
